use crate::types::USD;

pub const HACKATHON_COMPLETION_AMOUNT: USD = 40.;
pub const MEME_CONTEST_COMPLETION_AMOUNT: USD = 20.;
pub const WEBINAR_COMPLETION_AMOUNT: USD = 20.;
pub const CONTENT_COORDINATION_AMOUNT: USD = 25.;

pub const CA_REGISTER_REFERRAL_AMOUNT: USD = 5.;
pub const RECRUITMENT_REFERRAL_AMOUNT: USD = 10.;
pub const CAMPUS_MOU_AMOUNT: USD = 100.;
pub const NCD_COMPLETION_REFERRAL_AMOUNT: USD = 5.;
pub const NCD_FORM_FILLED_REFERRAL_AMOUNT: USD = 1.;

pub const HACKATHON_FIRST_PLACE_AMOUNT: USD = 150.;
pub const HACKATHON_SECOND_PLACE_AMOUNT: USD = 10.;
pub const HACKATHON_THIRD_PLACE_AMOUNT: USD = 5.;

pub const MEME_CONTEST_FIRST_PLACE_AMOUNT: USD = 75.;
pub const MEME_CONTEST_SECOND_PLACE_AMOUNT: USD = 50.;
pub const MEME_CONTEST_THIRD_PLACE_AMOUNT: USD = 35.;

pub const CA_BONUS_AMOUNT: USD = 125.;
