pub const ERR_NOT_PERMITTED: &str = "ERR_NOT_PERMITTED";
pub const ERR_PROPOSAL_NOT_FOUND: &str = "ERR_PROPOSAL_NOT_FOUND";
pub const ERR_BOUNTY_NOT_FOUND: &str = "ERR_BOUNTY_NOT_FOUND";
pub const ERR_MISCELLANEOUS_NOT_FOUND: &str = "ERR_MISCELLANEOUS_NOT_FOUND";
pub const ERR_REFERRAL_NOT_FOUND: &str = "ERR_REFERRAL_NOT_FOUND";
pub const ERR_REFERRAL_TOKEN_NOT_FOUND: &str = "ERR_REFERRAL_TOKEN_NOT_FOUND";
pub const ERR_GENERATING_RANDOM_NUMBER: &str = "ERR_GENERATING_RANDOM_NUMBER";
pub const ERR_CONTRACT_NOT_INITIALIZED: &str = "ERR_CONTRACT_NOT_INITIALIZED";
